# Generated by Django 3.2.6 on 2021-08-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ites_json',
            new_name='items_json',
        ),
    ]
